name: RayTraceAntiXray
main: com.vanillage.raytraceantixray.RayTraceAntiXray
version: 1.17.6
api-version: 1.21.11
# Authors and contributors of the plugin
authors:
  - stonar96
  - TauCu
  - metabrixkt
  - DaJokni
  - sofianedjerbi
  - RobinBr26
  - lRENyaaa
  - EuSouVoce
description: Paper plugin for server-side async multithreaded ray tracing to hide ores that are exposed to air using Paper Anti-Xray engine-mode 1.
load: STARTUP
depend: []
folia-supported: true
commands:
  raytraceantixray:
    description: All commands for RayTraceAntiXray.
    usage: '§cUsage: /<command> <timings <on, off>>|<reload>|<reloadchunks ?<player...>>'
    permission: raytraceantixray.command.raytraceantixray
    permission-message: §cYou don't have permissions.
